#!/bin/bash

#zenity --info
ans=$(zenity --icon=icons8-linux-50 --info --title "Changelog" --extra-button="Change Log" \
--ok-label="Cancel");

# Make the changelog
changelog () {
./changelog.mk
echo Which update?
read UPDATE
git add -A
git commit -m $UPDATE
echo  Running changelog a 2nd time to make sure we have the latest commit
./changelog.mk
git commit --amend  --no-edit
#echo Clean tree?
#    select yn in "yes" "no"; do
#        case $yn in
#    	yes ) make clean && make mrproper ;break;;
#    	no ) break;;
#        esac;
#    done
return
}

if [[ $ans == "Change Log" ]]; then
	changelog
fi
